Code4Newbies/config/routes.rb
Rails.application.routes.draw do
  resources :videos
  get 'page/home'

  get 'page/about'

  get 'page/contact'

   root 'page#home'

end

Code4Newbies/app/models/video.rb
class Video < ActiveRecord::Base
end

Code4Newbies/app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

Code4Newbies/app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:wistia, :description, :title)
    end
end

Code4Newbies/app/helpers/page_helper.rb
module PageHelper
end

Code4Newbies/app/helpers/videos_helper.rb
module VideosHelper
end

Code4Newbies/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Code4Newbies</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
  <title>Parallax Template - Materialize</title>

  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="css/style.css" type="text/css" rel="stylesheet" media="screen,projection"/>    
 <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
</head>
<body>
	<nav class="white" role="navigation">
    <div class="nav-wrapper container">
      <a id="logo-container" href="<%= page_home_path%>" class="brand-logo" style="color: white;
background-color: #FA4A86;">Code4Newbies</a>
      <ul class="right hide-on-med-and-down">       		         	
        <li><a href="<%= page_about_path %>"><i class="fa fa-info-circle"></i>
</a></li>
        <li><a href="<%= page_contact_path %>"><i class="fa fa-map-marker"></i>
</a></li>  		        
      </ul>

      <ul id="nav-mobile" class="side-nav">        	           		
        <li><a href="<%= page_about_path %>"><i class="fa fa-info-circle"></i>
</a></li>
        <li><a href="<%= page_contact_path %>"><i class="fa fa-map-marker"></i>
</a></li>    		
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>  
      <%= yield %>   
 <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="js/materialize.js"></script>
  <script src="js/init.js"></script>
</body>
</html>

Code4Newbies/app/views/page/about.html.erb
<div class="card z-depth-3">
	<div class="card-content white-text">	
		<div class="col">
			<div class="card-panel grey lighten-5 z-depth-1">
				<div class="row valign-wrapper">
					<div class="col m6">
						<%= image_tag "avatar.jpg", class: "circle responsive-img" %>
						<br/>
						<span class="black-text">
							<strong>I don't know what to say. Let the world tell you more...;D</strong>
						</span>	
					</div>
					<div class="col m6">
							<a class="twitter-timeline" data-dnt="true" href="https://twitter.com/Loki_Alcie" data-widget-id="530008100858630144">Tweet của @Loki_Alcie</a>
            <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>   
					</div>					
				</div>
			</div>
		</div>
	</div>
</div>

Code4Newbies/app/views/page/contact.html.erb
<div class="card z-depth-3">
	<div class="card-content white-text">	
		<div class="col">
			<div class="card-panel grey lighten-5 z-depth-1">
				<span class="black-text">
							<strong>I don't know what to say. Let the world tell you more...;D</strong>
				</span>	
				<div class="row valign-wrapper">
					<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3918.4339293396006!2d106.62398851434705!3d10.854563260715809!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752a20be133a37%3A0x2222564f53ae228d!2zQ8O0bmcgdmnDqm4gcGjhuqduIG3hu4FtIFF1YW5nIFRydW5n!5e0!3m2!1svi!2s!4v1459847280069" width="1269" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
				</div>
			</div>
		</div>
	</div>
</div>

Code4Newbies/app/views/page/home.html.erb
<div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot">
      <div class="container">
        <br><br>
        <h1 class="header center teal-text text-lighten-2">Parallax Template</h1>
        <div class="row center">
          <h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
        </div>
        <div class="row center">
          <a href="http://materializecss.com/getting-started.html" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Get Started</a>
        </div>
        <br><br>

      </div>
    </div>
    <div class="parallax"><img src="assets/background1.jpg" alt="Unsplashed background img 1"></div>
  </div>


  <div class="container">
    <div class="section">

      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">flash_on</i></h2>
            <h5 class="center">Speeds up development</h5>

            <p class="light">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components. Additionally, we refined animations and transitions to provide a smoother experience for developers.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">group</i></h2>
            <h5 class="center">User Experience Focused</h5>

            <p class="light">By utilizing elements and principles of Material Design, we were able to create a framework that incorporates components and animations that provide more feedback to users. Additionally, a single underlying responsive system across all platforms allow for a more unified user experience.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">settings</i></h2>
            <h5 class="center">Easy to work with</h5>

            <p class="light">We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>
          </div>
        </div>
      </div>

    </div>
  </div>


  <div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
      <div class="container">
        <div class="row center">
          <h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
        </div>
      </div>
    </div>
    <div class="parallax"><img src="assets/background2.jpg" alt="Unsplashed background img 2"></div>
  </div>

  <div class="container">
    <div class="section">

      <div class="row">
        <div class="col s12 center">
          <h3><i class="mdi-content-send brown-text"></i></h3>
          <h4>Contact Us</h4>
          <p class="left-align light">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque id nunc nec volutpat. Etiam pellentesque tristique arcu, non consequat magna fermentum ac. Cras ut ultricies eros. Maecenas eros justo, ullamcorper a sapien id, viverra ultrices eros. Morbi sem neque, posuere et pretium eget, bibendum sollicitudin lacus. Aliquam eleifend sollicitudin diam, eu mattis nisl maximus sed. Nulla imperdiet semper molestie. Morbi massa odio, condimentum sed ipsum ac, gravida ultrices erat. Nullam eget dignissim mauris, non tristique erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
        </div>
      </div>

    </div>
  </div>


  <div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
      <div class="container">
        <div class="row center">
          <h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
        </div>
      </div>
    </div>
    <div class="parallax"><img src="assets/background3.jpg" alt="Unsplashed background img 3"></div>
  </div>

  <footer class="page-footer teal">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Company Bio</h5>
          <p class="grey-text text-lighten-4">We are a team of college students working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated.</p>


        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Settings</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Connect</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Made by <a class="brown-text text-lighten-3" href="http://materializecss.com">Materialize</a>
      </div>
    </div>
  </footer>  

Code4Newbies/app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field">    
    <%= f.text_field :wistia, :placeholder => 'Link', :length => '10' %>
  </div>
  <div class="input-field">    
    <%= f.text_field :title, :placeholder => 'Title', :length => '20'  %>
  </div>
  <div class="input-field">    
    <%= f.text_area :description, :placeholder => 'Description', :length => '800', :class => 'materialize-textarea'  %>
  </div>
  <br/>
  <button class="btn waves-effect waves-light" type="submit" name="action">Submit</button>
  <a href="<%= videos_path %>" class="btn waves-effect waves-light" name="action">Back</a>
<% end %>

Code4Newbies/app/views/videos/edit.html.erb
<div class="card z-depth-3">
	<div class="card-content">	
		<div class="col">
			<div class="card-panel grey lighten-5 z-depth-1">
				<h1>Editing Video</h1>
				<%= render 'form' %>			
			</div>
		</div>
	</div>
</div>

Code4Newbies/app/views/videos/index.html.erb
<div class="card z-depth-3">
  <div class="card-content"> 
    <div class="col">     
        <p id="notice"><%= notice %></p>
        <%= link_to new_video_path, :class => 'btn-floating btn-large waves-effect waves-light red' do %>
          <i class="fa fa-plus-square"></i>
        <% end %>
        <ul class="collapsible" data-collapsible="accordion">
          <% @videos.each do |video| %>
            <li>
              <div class="collapsible-header">
                <i class="fa fa-book"></i>
                <%= link_to video.title, video %>
                <span class="right">
                  <%= link_to edit_video_path(video) do %>
                    <i class="fa fa-pencil fa-fw"></i>
                  <% end %>
                  <%= link_to video, method: :delete, data: { confirm: 'Are you sure?' } do %>
                    <i class="fa fa-trash-o fa-fw"></i>
                  <% end %>
                </span>
              </div>
              <div class="collapsible-body"><p> <%= video.description %></p></div>
            </li>
          <% end %>
        </ul>
    </div>
  </div>
</div>

Code4Newbies/app/views/videos/new.html.erb
<div class="card z-depth-3">
	<div class="card-content">	
		<div class="col">
			<div class="card-panel grey lighten-5 z-depth-1">
				<h1>New Video</h1>
				<%= render 'form' %>				
			</div>
		</div>
	</div>
</div>

Code4Newbies/app/views/videos/show.html.erb
<div class="card z-depth-3">
	<div class="card-content">	
		<p id="notice"><%= notice %></p>
		<div class="col m3">
			<div class="collection">
				<%= @videos.each do |video|%>
					<%= link_to video.title,video, :class => 'collection-item' %>
				<% end %>
			</div>
		</div>
		<div class="col m9">
			
		</div>		
	</div>
</div>